language: python
python:
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
env:
  - DJANGO_VERSION=1.7.8
  - DJANGO_VERSION=1.8.2
install:
  - pip install .
  - pip install -q django==$DJANGO_VERSION
  - pip install coveralls
script:
  - env PYTHONPATH=`pwd` coverage run --source=django_image example/manage.py test
after_success:
  coveralls
