language: python
python:
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
env:
  - DJANGO_VERSION=1.4.20
  - DJANGO_VERSION=1.5.12
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.8
  - DJANGO_VERSION=1.8.2
install:
  - pip install -q django==$DJANGO_VERSION
  - pip install -q -r example/requirements.txt
  - pip install coveralls
script:
  - env PYTHONPATH=`pwd` coverage run --source=django_su example/manage.py test django_su
after_success:
  coveralls
matrix:
  exclude:
    - python: "3.4"
      env: DJANGO_VERSION=1.4.20
    - python: "3.3"
      env: DJANGO_VERSION=1.4.20
    - python: "3.2"
      env: DJANGO_VERSION=1.4.20
    - python: "2.6"
      env: DJANGO_VERSION=1.7.8
    - python: "2.6"
      env: DJANGO_VERSION=1.8.2
